### ISSUE TITLE
Problems with LLVM

### ISSUE THREAD

**Issue by AbhinavMir** [maekawatoshiki/rucc#3]
The command to install LLVM-4.0 returns this error on Debian

```
E: Unable to locate package llvm-4.0
E: Couldn't find any package by glob 'llvm-4.0'
E: Couldn't find any package by regex 'llvm-4.0'
E: Unable to locate package llvm-4.0-dev
E: Couldn't find any package by glob 'llvm-4.0-dev'
E: Couldn't find any package by regex 'llvm-4.0-dev'
```

Could you update the project to use latest LLVM? I don't use Rust, otherwise I'd have had sent a pull request 😀.
Thanks!

**Comment by maekawatoshiki** [comment]
Thank you for reporting. LLVM 4.0 is surely old. I'll migrate to newer one.

**Comment by AbhinavMir** [comment]
Thanks!

**Comment by maekawatoshiki** [comment]
I just upgraded LLVM. By the way, it seems currently rucc sometimes causes SEGV.

**Comment by maekawatoshiki** [comment]
I'm now working on making a compiler infrastructure (named cilk), and making a small C compiler based on cilk.
https://github.com/maekawatoshiki/cilk/tree/master/cilkcc
This is more readable so will help you.

**Comment by AbhinavMir** [comment]
Thank you, will give it a read!
